name: registerapp_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # sdk: ">=2.10.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:   
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.19.1

  # database
  sqflite: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  # sqflite: ^1.3.2+2

  fluttertoast: ^8.0.7
  intl: ^0.17.0
  # intl: ^0.16.1
  
  equatable: ^2.0.3
  http: ^0.13.3
  flutter_local_notifications: ^6.0.0
  firebase_messaging: ^10.0.4
  firebase_core: ^1.4.0

  # web socket client
  # web_socket_channel: ^2.1.0

  device_info: ^2.0.2

  # create qrcode
  qr_flutter: ^4.0.0
  screenshot: ^1.2.3
  share: ^2.0.4

  # getx 
  get: ^4.3.8

  socket_io_client: ^1.0.0

  # mqtt
  # mqtt_client: ^9.6.1

  # calendar selector
  syncfusion_flutter_datepicker: 20.1.52
  syncfusion_localizations: 20.1.52
  flutter_rounded_date_picker: 1.0.4
  timeago: ^3.2.2

  flutter_easyloading: ^3.0.5

  # buddhist_datetime_dateformat: ^1.0.6
  # flutter_datetime_picker: ^1.5.1
  # awesome_dialog: ^2.1.0
  # time_range_picker: ^2.0.1
  # font_awesome_flutter: ^8.11.0
  # intl: ^0.17.0
  # google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto/Roboto-Thin.ttf
    #     - asset: assets/fonts/Roboto/Roboto-Italic.ttf
    #       style: italic
    #     - asset: assets/fonts/Roboto/Roboto-Bold.ttf
    #       weight: 700


    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt/Prompt-Light.ttf
          weight: 500
        - asset: assets/fonts/Prompt/Prompt-Medium.ttf
          weight: 600
        - asset: assets/fonts/Prompt/Prompt-Black.ttf
          weight: 700

        # - asset: assets/fonts/Arial/ArialTh.ttf
        # - asset: assets/fonts/Arial/ARIBL0.ttf
        #   weight: 500
        # - asset: assets/fonts/Prompt/Prompt-Medium.ttf
        #   weight: 600
        # - asset: assets/fonts/Prompt/Prompt-Black.ttf
        #   weight: 700